### ISSUE TITLE
New Webkit versions

### ISSUE THREAD

**Issue by bpiec** [webkitdotnet/webkitdotnet#21]
Is it possible to build the library with new Webkit version included? How to do this?

**Comment by jrpbuilds** [comment]
I've attempted to rebuild an updated version of WebKit quite a few times but something usually either goes wrong or comes up in life.

Start here being very careful not to miss anything to setup a build environment: http://blog.ashodnakashian.com/2012/01/building-webkit-on-windows-7-with-vs2010/

You best bet is then trying to build the nightly: http://nightly.webkit.org/

That way you shouldn't have as much trouble other than setting up a build environment. Google should return fixes for most issues setup related.

Good luck!

**Comment by peterdn** [comment]
I compiled WebKit Cairo r109587 which can be found in the develop branch.

If you want to have a go yourself, the blog post that @painejake linked to looks good.  Also, @bfulgham is the authority on WebKit Cairo, and his blog details build requirements etc http://whtconstruct.blogspot.co.uk/

Checking out the buildbot is also a good way to determine if build problems are your fault, or if the tree is just broken http://build.webkit.org/waterfall

**Comment by bfulgham** [comment]
Hi Peter,

I'm trying to get the testing infrastructure running more reliably. Right now it's timing out on the build machine, but at least it's running the right target now.

I'm also trying to update the Cairo software to use OpenGL for some rendering, since it's reliably available back to Win XP, while The Direct2D stuff is an optional Vista install, and isn't available on XP at all.

I'm trying to do a better job of reporting progress, but it's an uphill climb. :(

-Brent

**Comment by peterdn** [comment]
Thanks for the update, Brent.  I might see what I can do to help out, if I get the time.
